name: Telegram PR Notify

on:
  push:
    branches: 
      - '**'  # This means ALL branches
  pull_request:
    types: [opened, closed, reopened]

jobs:
  telegram:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ðŸ“Œ *${{ github.event.action | capitalize }} Pull Request*
            
            *Repository:* ${{ github.repository }}
            *Title:* ${{ github.event.pull_request.title }}
            *Author:* ${{ github.event.pull_request.user.login }}
            *Number:* #${{ github.event.number }}
            
            [View Pull Request](${{ github.event.pull_request.html_url }})
          parse_mode: markdown